import { sql } from 'drizzle-orm';
import { sqliteTable, text, integer, index } from 'drizzle-orm/sqlite-core';

import { user } from './auth';

// A self-service fallback for "forgot my password AND lost access to my email" — the other
// two recovery paths (email-based reset, the CLI/break-glass owner-recovery tools in
// docs/ARCHITECTURE.md §10) both assume the operator still has one of those. Codes are
// generated by the owner for their own account only (never for anyone else), hashed at rest
// (SHA-256 — cheap by design, since a code is a single-use, rate-limited, high-entropy random
// string rather than a user-chosen password that needs to resist offline guessing), single-use,
// and only ever shown to the owner once at generation time; this table stores no plaintext.
// Cascade-deletes with the user — a code for a since-deleted account can never be redeemed.
export const recoveryCode = sqliteTable(
  'recovery_code',
  {
    id: text('id')
      .primaryKey()
      .$defaultFn(() => crypto.randomUUID()),
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    codeHash: text('code_hash').notNull(),
    used: integer('used', { mode: 'boolean' }).notNull().default(false),
    createdAt: integer('created_at', { mode: 'timestamp' })
      .notNull()
      .default(sql`(unixepoch())`),
  },
  (table) => [index('recovery_code_userId_idx').on(table.userId)],
);

export type RecoveryCode = typeof recoveryCode.$inferSelect;
export type NewRecoveryCode = typeof recoveryCode.$inferInsert;
