import { desc, eq, session } from '@kenresoft-cms/database';
import type { Database } from '@kenresoft-cms/database';

// auth.ts is generated by @better-auth/cli (apps/api/src/lib/auth-options.ts's pinned-version
// note) and doesn't export a Session type itself — inferred here instead of hand-adding one to
// a generated file.
export type Session = typeof session.$inferSelect;

export function listSessionsForUser(db: Database, userId: string): Promise<Session[]> {
  return db.query.session.findMany({
    where: eq(session.userId, userId),
    orderBy: desc(session.updatedAt),
  });
}

export function getSessionById(db: Database, id: string): Promise<Session | undefined> {
  return db.query.session.findFirst({ where: eq(session.id, id) });
}

// Deleting the row is enough to kill the session — better-auth's getSession looks up the
// session by its token against this same table on every authenticated request, so a missing
// row is indistinguishable from an expired one. No better-auth admin-plugin dependency needed
// (deliberately not used here, apps/api/src/lib/auth-options.ts) for something this direct.
export async function deleteSession(db: Database, id: string): Promise<void> {
  await db.delete(session).where(eq(session.id, id));
}

// Called when disabling a user, as defense-in-depth alongside requireSession's own
// result.user.disabled check — a device already holding a valid session cookie is cut off
// immediately rather than waiting for that session to expire naturally.
export async function deleteAllSessionsForUser(db: Database, userId: string): Promise<void> {
  await db.delete(session).where(eq(session.userId, userId));
}

// better-auth has no public API for setting a custom session additionalField, so
// POST /api/v1/admin/security/elevate writes elevatedUntil directly through this repository —
// same layer every other session mutation in this file already goes through.
export async function setSessionElevatedUntil(db: Database, id: string, elevatedUntil: Date): Promise<void> {
  await db.update(session).set({ elevatedUntil }).where(eq(session.id, id));
}
